heat_template_version: 2013-05-23

resources:
  external_network:
    type: OS::Neutron::ProviderNet
    properties:
      name: external_network
      network_type: flat
      physical_network: public
      shared: true
      router_external: true
  router1:
    type: OS::Neutron::Router
    properties:
      name: router1
      external_gateway_info:
        network: { get_resource: external_network }


  public_subnet:
        type: OS::Neutron::Subnet
        properties:
          network_id: { get_resource: external_network }
          cidr:  172.24.4.0/28
          gateway_ip:  172.31.16.1
          dns_nameservers:
            - 8.8.8.8
