heat_template_version: 2015-04-30

description: Create a new Project. Assign a user and user-role pair.

parameters:
  project_name:
    type: string
  user_role:
    type: string
  project_user:
    type: string
  project_user_passwd:
    type: string

resources:
  project:
    type: OS::Keystone::Project
    properties:
      name: { get_param: project_name }
      domain: default
      description: Redhat assignment project
  user:
    type: OS::Keystone::User
    properties:
      name: { get_param: project_user }
      domain: default
      description: my user
      default_project: { get_resource: project }
      password: { get_param: project_user_passwd }
      roles:
        - role: { get_param: user_role}
          project: { get_resource: project }
#
#
# parameters:
#   project_name: redhat-cloud-assignment
#   user_role:  _member_
#   project_user: ahmed
#   project_user_passwd: 123
